# Generated by Django 4.2.1 on 2023-06-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dish_search", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("items", models.TextField()),
                ("latitude", models.FloatField()),
                ("details", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="Dish",
        ),
    ]
